name: mllab
channels:
    - conda-forge
dependencies:
    - python==3.6.3
    - matplotlib==2.1.1
    - jupyter==1.0.0
    - future==0.16.0
    - scikit-image==0.13.1
    - scipy==1.0.0
    - scikit-learn==0.19.1
    - pip:
        - gym==0.10.5 #'gym[all]'
        - msgpack==0.5.6
        - argparse==1.4.0
        - tensorflow==1.7.0
        - stable-baselines==2.0.0

